---
# This workflow integrates qwiet.ai preZero with GitHub
# Visit https://docs.shiftleft.io for help
name: qwiet.ai

on:
  pull_request:
  workflow_dispatch:

jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java JDK v8.0.x
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 8.0.x

    #- name: Setup Gradle 8.10
    #  uses: gradle/actions/setup-gradle@v3
    #  with:
    #    gradle-version: "5.1.1" # Quotes required to prevent YAML converting to number
   # - name: Build with Gradle 8.10
    #  run: ./gradlew properties -p packages/clients/android
       #run: gradle build -p packages/clients/android
        
    #- name: Setup Android SDK Tools
     # uses: android-actions/setup-android@v3.2.1
      
    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl

    - name: preZero Static Analysis
      run: |
        ${GITHUB_WORKSPACE}/sl --version
        SHIFTLEFT_SBOM_GENERATOR=1 ${GITHUB_WORKSPACE}/sl analyze --strict --wait \
          --app GoatlinCheck --verbose \
          --tag branch=${{ github.head_ref }} \
          # --kotlin packages/clients/.
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        SHIFTLEFT_API_HOST: www.shiftleft.io
        SHIFTLEFT_GRPC_TELEMETRY_HOST: telemetry.shiftleft.io:443
        SHIFTLEFT_GRPC_API_HOST: api.shiftleft.io:443

#   Build-Rules:
#     runs-on: ubuntu-latest
#     permissions: write-all
#     needs: NextGen-Static-Analysis
#     steps:
#     - uses: actions/checkout@v3
#     - name: Download ShiftLeft CLI
#       run: |
#         curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
#     - name: Validate Build Rules
#       run: |
#         ${GITHUB_WORKSPACE}/sl check-analysis --app GoatlinCheck \
#             --github-pr-number=${{github.event.number}} \
#             --github-pr-user=${{ github.repository_owner }} \
#             --github-pr-repo=${{ github.event.repository.name }} \
#             --github-token=${{ secrets.GITHUB_TOKEN }}
#       env:
#         # SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
#
#         SHIFTLEFT_API_HOST: www.shiftleft.io
#         SHIFTLEFT_GRPC_TELEMETRY_HOST: telemetry.shiftleft.io:443
#         SHIFTLEFT_GRPC_API_HOST: api.shiftleft.io:443
#


